version: '3.10'  # Docker Compose 파일 버전

services:  # 실행할 컨테이너 서비스들을 정의
  web:  # 웹 애플리케이션(Django) 이름
    build:
      context: .  # 현재 디렉토리를 빌드 컨텍스트로 사용 (Dockerfile 및 소스코드 위치)
      dockerfile: Dockerfile  # 사용할 Dockerfile 이름
    container_name: project-portfolio  # 생성될 컨테이너 이름

    ports:
      - "8000:8000"  # 호스트:컨테이너 포트 바인딩

    volumes:
      - .:/app  # 현재 디렉토리를 컨테이너의 /app에 마운트

    environment:
      - PYTHONDONTWRITEBYTECODE=1  # 파이썬 바이트코드 캐시 비활성화 (optional)
      - PYTHONUNBUFFERED=1  # 로그 출력 버퍼링 비활성화 (optional)

    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]  
    # 컨테이너 시작 시 실행할 명령어
    # Django 서버를 모든 IP에서 8000포트로 실행한다는 의미